# Generated by Django 5.1.1 on 2024-11-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_blog_post_tags_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
