# Generated by Django 5.1.1 on 2024-11-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_blog_post_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
