# Generated by Django 5.1.1 on 2024-11-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_blog_post_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_post',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='rejection_reason',
        ),
        migrations.AddField(
            model_name='blog_post',
            name='approval_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
